# Generated by Django 5.1.4 on 2025-01-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaser',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
