# Generated by Django 5.1.4 on 2025-01-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('category', models.IntegerField(choices=[(1, 'Clothes'), (2, 'Food'), (3, 'Services'), (4, 'Health'), (5, 'Miscellaneous')])),
            ],
        ),
    ]
