# Generated by Django 5.1.4 on 2025-01-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.TextField(null=True, unique=True),
        ),
    ]
