# Generated by Django 5.1.5 on 2025-08-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0003_alter_purchase_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchase",
            options={"ordering": ["-name"]},
        ),
        migrations.AlterField(
            model_name="purchase",
            name="category",
            field=models.IntegerField(
                choices=[
                    (1, "Clothes"),
                    (2, "Food"),
                    (3, "Services"),
                    (4, "Health"),
                    (5, "Miscellaneous"),
                    (6, "Household"),
                    (7, "Shoes"),
                    (8, "Electronics"),
                    (9, "Books"),
                ],
                default=2,
            ),
        ),
    ]
