# Generated by Django 4.1.6 on 2023-02-12 23:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('purchased_at_store', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('name', models.TextField(null=True)),
                ('category', models.IntegerField(choices=[(1, 'Clothes'), (2, 'Food'), (3, 'Services'), (4, 'Health'), (5, 'Miscellaneous')])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseorder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
    ]
