# Generated by Django 5.1.4 on 2025-01-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
