# Generated by Django 5.1.5 on 2025-08-19 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0004_alter_purchase_options_alter_purchase_category"),
        ("purchases", "0003_purchaselineitem_quantity_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaselineitem",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="line_items",
                to="purchase.purchase",
            ),
        ),
        migrations.AlterField(
            model_name="purchaselineitem",
            name="quantity_unit",
            field=models.IntegerField(
                choices=[(1, "Piece"), (2, "Grams"), (3, "Mlitres")], default=1
            ),
        ),
    ]
